# -*- coding: utf-8 -*-
"""LeNET Architecture.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10PtCC1bn_O1Z1O0QrzPr2BktJaWUS-HT
"""

import tensorflow
from tensorflow import keras
from keras.layers import Dense, Conv2D, AveragePooling2D, Flatten
from keras.models import Sequential

from keras.datasets import mnist

(X_train,y_train), (X_test,y_test) = mnist.load_data()

"""LeNET ARCHITECTURE"""

model = Sequential()

model.add(Conv2D(6, kernel_size=(5,5), padding = 'valid', activation='tanh', input_shape=(32,32,1)))
model.add(AveragePooling2D(pool_size=(2,2), strides=2, padding='valid'))

model.add(Conv2D(16, kernel_size=(5,5), padding = 'valid', activation='tanh'))
model.add(AveragePooling2D(pool_size=(2,2), strides=2, padding='valid'))

model.add(Flatten())

model.add(Dense(120, activation='tanh'))
model.add(Dense(84, activation='tanh'))
model.add(Dense(10, activation='softmax'))

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

model.summary()

