# -*- coding: utf-8 -*-
"""lstm-project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e55Lnl0I0gFgzrbOwEAGsqmnKKwAWpRO
"""

faqs = """The only way to do great work is to love what you do.
Success is not final, failure is not fatal, it is the courage to continue that counts.
Believe you can and you are halfway there.
Do something today that your future self will thank you for.
The future depends on what you do today.
It always seems impossible until it is done.
Dream big and dare to fail.
The harder you work, the luckier you get.
Do not watch the clock; do what it does. Keep going.
Great things are done by a series of small things brought together.
The secret of getting ahead is getting started.
Your limitation is only your imagination.
Push yourself because no one else is going to do it for you.
Small progress is still progress.
Success comes from consistency, not perfection.
Discipline is choosing between what you want now and what you want most.
Do not stop when you are tired. Stop when you are done.
Every expert was once a beginner.
The journey of a thousand miles begins with a single step.
A little progress each day adds up to big results.
Your future is created by what you do today, not tomorrow.
Do not be afraid to start over. This time you are not starting from scratch.
Difficult roads often lead to beautiful destinations.
The best view comes after the hardest climb.
You become what you believe.
Action is the foundational key to all success.
Success is the sum of small efforts repeated day after day.
The difference between ordinary and extraordinary is that little extra.
If you want to fly, give up everything that weighs you down.
You do not have to be perfect to make progress.
The greatest glory in living lies not in never falling, but in rising every time we fall.
It is never too late to become what you might have been.
Everything you can imagine is real.
The mind is everything. What you think you become.
What lies behind us and what lies before us are tiny matters compared to what lies within us.
Happiness depends upon ourselves.
Life is really simple, but we insist on making it complicated.
In the middle of difficulty lies opportunity.
Turn your wounds into wisdom.
Do not let yesterday take up too much of today.
Life is short, so make every moment count.
Be yourself; everyone else is already taken.
The purpose of our lives is to be happy.
Keep your face always toward the sunshine, and shadows will fall behind you.
Where there is a will, there is a way.
Nothing is impossible to a willing heart.
The only person you are destined to become is the person you decide to be.
Be not afraid of going slowly, be afraid only of standing still.
A journey is best measured in friends rather than miles.
Life is a succession of lessons which must be lived to be understood.
Knowledge is power.
Learning never exhausts the mind.
The beautiful thing about learning is that nobody can take it away from you.
Education is the passport to the future.
The more you learn, the more you realize how much you do not know.
Curiosity is the beginning of wisdom.
Never stop learning because life never stops teaching.
Mistakes are proof that you are trying.
Failure is simply the opportunity to begin again, this time more intelligently.
Do not fear failure. Fear being in exactly the same place next year as you are today.
Failure does not mean you are a failure. It means you have not succeeded yet.
Sometimes you win, sometimes you learn.
A mistake repeated more than once is a decision.
Success is built on failure, frustration, and even catastrophe.
Do not let failure define you. Let it teach you.
The comeback is always stronger than the setback.
Every failure brings you one step closer to success.
Hard work beats talent when talent does not work hard.
Talent gets you started, but hard work keeps you going.
Success requires sacrifice.
Work hard in silence and let success make the noise.
Focus on your goal, not the obstacle.
Consistency transforms average into excellence.
You cannot build a reputation on what you are going to do.
Great achievements require time and patience.
Patience is not the ability to wait, but the ability to keep a good attitude while waiting.
Do not compare your beginning to someone else's middle.
Your only competition is who you were yesterday.
Focus on becoming better, not being better than someone else.
The strongest people are not those who never struggle, but those who never give up.
Strength grows in the moments when you think you cannot go on.
Courage is not the absence of fear, but the decision that something else is more important.
Be brave enough to live the life you want.
Fear is temporary. Regret lasts longer.
Do one thing every day that scares you.
Courage starts with showing up.
You are stronger than you think.
Believe in yourself even when nobody else does.
Your attitude determines your direction.
A positive mindset creates positive results.
Change your thoughts and you can change your world.
Your thoughts become your actions, your actions become your habits, and your habits become your character.
What you focus on grows.
Choose progress over perfection.
Stay patient and trust your journey.
The best time to plant a tree was twenty years ago. The second best time is now.
Do not wait for opportunity. Create it.
Opportunities do not happen. You create them.
If opportunity does not knock, build a door.
The future belongs to those who prepare for it today.
Your dreams are worth the effort.
Make your vision so clear that your fears become irrelevant.
A goal without a plan is just a wish.
Set goals, work hard, stay focused, and never give up."""

import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

tokenizer = Tokenizer()

tokenizer.fit_on_texts([faqs])

len(tokenizer.word_index)

tokenizer.word_index

input_sequences = []
for sentence in faqs.split('\n'):
  tokenized_sentence = tokenizer.texts_to_sequences([sentence])[0]

  for i in range(1,len(tokenized_sentence)):
    input_sequences.append(tokenized_sentence[:i+1])

input_sequences

max_len = max([len(x) for x in input_sequences])

from tensorflow.keras.preprocessing.sequence import pad_sequences
padded_input_sequences = pad_sequences(input_sequences, maxlen = max_len, padding='pre')

padded_input_sequences

x = padded_input_sequences[:,:-1]

y = padded_input_sequences[:,-1]

X.shape

y.shape

from tensorflow.keras.utils import to_categorical
y = to_categorical(y,num_classes=381)

y.shape

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

model = Sequential()
model.add(Embedding(381, 100)) # Removed input_length as it's deprecated
model.add(LSTM(150, return_sequences=True)) # Added return_sequences=True for stacked LSTMs
model.add(LSTM(150))
model.add(Dense(381, activation='softmax'))

model.compile(loss='categorical_crossentropy', optimizer='adam',metrics=['accuracy'])

model.summary()

model.fit(X,y,epochs=100)

import numpy as np
import time
text = "The only way"

for i in range(10):
  # tokenize
  token_text = tokenizer.texts_to_sequences([text])[0]
  # padding
  padded_token_text = pad_sequences([token_text], maxlen=56, padding='pre')
  # predict
  pos = np.argmax(model.predict(padded_token_text))

  for word,index in tokenizer.word_index.items():
    if index == pos:
      text = text + " " + word
      print(text)
      time.sleep(2)

tokenizer.word_index

