# -*- coding: utf-8 -*-
"""Functional_API (Complex).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cT8eqPahvziIdF-J6Oe3Cbv8Ssxa2ox-
"""

from keras.layers import *
from keras.models import Model

inputA = Input(shape=(32,))
inputB = Input(shape=(128,))

x = Dense(8,activation = 'relu')(inputA)
x1 = Dense(4, activation='relu')(x)

y = Dense(64, activation='relu')(inputB)
y1 = Dense(32, activation='relu')(y)
y2 = Dense(4,activation='relu')(y1)

combined = concatenate([x1,y2])

z = Dense(2, activation='relu')(combined)
z1 = Dense(1, activation='linear')(z)

model = Model(inputs=[inputA,inputB], outputs=z1)

from keras.utils import plot_model
!apt-get install --reinstall graphviz
!pip install --upgrade pydot graphviz
plot_model(model,show_shapes = True)

