# -*- coding: utf-8 -*-
"""Data-Augmentation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i7OXVfG_I7lHAEhDXtBwwWaKRM9ArU7E
"""

from tensorflow.keras.preprocessing import image
from tensorflow.keras.preprocessing.image import ImageDataGenerator

img = image.load_img('/cat.4.jpg',target_size=(200,200))

import matplotlib.pyplot as plt

plt.imshow(img)

"""BLOCK FOR DATA AUGMENTATION

"""

datagen = ImageDataGenerator(
      rotation_range=40,
      width_shift_range=0.2,
      height_shift_range=0.2,
      shear_range=0.2,
      zoom_range=0.2,
      horizontal_flip=True,
)


img = image.img_to_array(img)

img.shape

input_batch = img.reshape(1,200,200,3)

from os import makedirs
i = 0

# Create the directory if it doesn't exist
makedirs('aug', exist_ok=True)

for output in datagen.flow(input_batch, batch_size=1, save_to_dir = 'aug', save_prefix='aug', save_format='jpeg'):
  i = i + 1

  if i == 10:
    break

input_batch.shape

