# -*- coding: utf-8 -*-
"""keras-tunning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wyRTBT8aMMq1eW5XFueQEZC3Jn5iVzDu
"""

import pandas as pd
import numpy as np

df = pd.read_csv('diabetes.csv')

df.head(4)

df.corr()['Outcome']

X = df.iloc[:,:-1].values
y =df.iloc[:,-1].values

X

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

X

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

model = Sequential()

model.add(Dense(32,activation='relu',input_dim=8))

model.add(Dense(1,activation='sigmoid'))

model.compile(optimizer='Adam',loss='binary_crossentropy',metrics=['accuracy'])

model.fit(batch_size=32,x=X_train,y=y_train,epochs=10,validation_data=(X_test,y_test))

pip install -U keras-tuner

import kerastuner as kt

def build_model(hp):

  model = Sequential()
  model.add(Dense(32,activation='relu', input_dim=8))
  model.add(Dense(1,activation='sigmoid'))
  optimizer = hp.Choice('optimizer',values=['adam','sgd','rmsprop'])
  model.compile(optimizer=optimizer,loss='binary_crossentropy',metrics=['accuracy'])
  return model

tuner = kt.RandomSearch(build_model,objective='val_accuracy',max_trials=5)

tuner.search(X_train,y_train,epochs=5,validation_data=(X_test,y_test))

tuner.get_best_hyperparameters()[0].values

model = tuner.get_best_models(num_models=1)[0]

model.fit(X_train,y_train,epochs=100,initial_epoch=6,validation_data=(X_test,y_test))

def build_model(hp):

  model = Sequential()

  units = hp.Int('units',8,128,step=8)
  model.add(Dense(units=units,activation='relu',input_dim=8))

  model.add(Dense(1,activation='sigmoid'))

  model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

  return model

tuner = kt.RandomSearch(build_model,objective='val_accuracy',max_trials=5, project_name='my_new_tuning_project')

tuner.search(X_train,y_train,epochs=5,validation_data=(X_test,y_test))

tuner.get_best_hyperparameters()[0].values

model = tuner.get_best_models(num_models=1)[0]

model.fit(X_train,y_train,epochs=100,initial_epoch=6,validation_data=(X_test,y_test))

def build_model(hp):
  model = Sequential()

  model.add(Dense(72,activation='relu',input_dim=8))

  for i in range(hp.Int('num_layers', min_value = 1, max_value = 10)):
    model.add(Dense(72,activation='relu'))

  model.add(Dense(1,activation='sigmoid'))

  model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

  return model

tuner = kt.RandomSearch(build_model,objective='val_accuracy',max_trials=5,project_name='my_new_tuning_project')

tuner.search(X_train,y_train,epochs=5,validation_data=(X_test,y_test))

tuner.get_best_hyperparameters()[0].values

model = tuner.get_best_models(num_models=1)[0]

model.fit(X_train,y_train,epochs=100,initial_epoch=6,validation_data=(X_test,y_test))

def build_model(hp):

  model = Sequential()

  counter = 0

  for i in range(hp.Int('num_layers'),min_value=1,max_value=10):
    if counter == 0:
      model.add(Dense
       (hp.Int('units' + str(i), min_value=8, max_value=128, step=8),
        activation= hp.Choice('activation' + str(i), values = ['relu', 'tanh', 'sigmoid']),
        input_dim = 8))

    else:
      model.add(Dense
       (hp.Int('units' + str(i), min_value=8, max_value=128, step=8),
        activation= hp.Choice('activation' + str(i), values = ['relu', 'tanh', 'sigmoid'])
        )
       )
      counter += 1

      model.add(Dense(1,activation='sigmoid'))

      model.compile(optimizer=hp.Choice('optimizer',values=['adam','sgd','rmsprop']),loss='binary_crossentropy',metrics=['accuracy'])

      return model

    model.compile(optimizer=hp.Choice('optimizer',values=['adam','sgd','rmsprop']),loss='binary_crossentropy',metrics=['accuracy'])

    return model

kt.RandomSearch(build_model,objective='val_accuracy',max_trials=5,project_name='my_new_tuning_project')

tuner.search(X_train,y_train,epochs=5,validation_data=(X_test,y_test))

tuner.get_best_hyperparameters()[0].values

model = tuner.get_best_models(num_models=1)[0]

model.fit(X_train,y_train,epochs=100,initial_epoch=6,validation_data=(X_test,y_test))

